### ISSUE TITLE
Flash commands polish

### ISSUE THREAD

**Issue by darsain** [darsain/uosc#23]
![image](https://user-images.githubusercontent.com/538801/82413024-f1183200-9a74-11ea-87b8-f3cf280beb5a.png)

**Comment by FichteFoll** [comment]
flash-timeline is cancelled as soon as I move my mouse over the video. The flash should have priority over `autohide=yes`.

**Comment by darsain** [comment]
> flash-timeline is cancelled as soon as I move my mouse over the video. Happens regardless of autohide=yes.

flash-timeline doesn't do that. I think you mean peek-timeline, in which case that works as intended:

>peek-timeline
>Expands the bottom timeline until pressed again, **or next mouse move**. Useful to check times during playback.

It's purpose is to check times in timeline if you don't want to bother moving mouse, so any mouse movement resets it.

**Comment by FichteFoll** [comment]
You're right, I think I mixed what I bound my tab key to be something of both `peek-timeline` and `flash-timeline`, i.e. I thought the peeking bar would just disappear after the autohide timeout instead of until the next mouse move. Both ways are fine to me, so it's probably just wrong expectations on my part.
