### ISSUE TITLE
 The background and foreground colors of the progress bar are not aligned and will deviate by about 1 pixel

### ISSUE THREAD

**Issue by scetus** [darsain/uosc#4]
The seek bar is the same

**Comment by darsain** [comment]
If you are talking about the top and bottom 1px borders matching background color, that's on purpose.

Top 1px bar ensures the elapsed bar can be seen even when video background is super light.

Bottom 1px is enabled only in no-border windowed mode so the bar can be visible when window is positioned above some light background. Otherwise it can look like the bar is part of the background window.

**Comment by scetus** [comment]
Is there a setting option that allows me to control the size of this border?
I want to make the effect of youtube player

**Comment by darsain** [comment]
I'll add it in next version.

**Comment by scetus** [comment]
thank you very much！

**Comment by darsain** [comment]
It's not resolved yet.

**Comment by darsain** [comment]
Added in 2.0.0.
