### ISSUE TITLE
 Is it possible to set the activation area for the time bar

### ISSUE THREAD

**Issue by scetus** [darsain/uosc#5]
sorry for my poor english

In the new version, the time bar and search bar have been merged. I must only activate the time bar when I fast forward

In the old version, I can fast forward by clicking the mouse when the display time bar is not activated by setting

In the old version, my configuration file can be written like this

seekbar_size=100
seekbar_size_fullscreen=200
seekbar_opacity=0
seekbar_chapters=
seekbar_chapters_opacity=0.8

progressbar_size=1.5
progressbar_size_fullscreen=3
progressbar_opacity=1
progressbar_chapters=lines-bottom
progressbar_chapters_opacity=1

**Comment by scetus** [comment]
Regarding the function of this response area, there is a similar reference in another script
“hover-zone”

[https://github.com/torque/mpv-progressbar](url)

This function will be convenient for quick positioning but will not occupy a large screen area

**Comment by scetus** [comment]
Suddenly remembered that the function of binding the left mouse button in that script was complicated to implement. No need to refer to it, as long as it can provide the function of configuring the time bar and the search bar in the previous version separately

**Comment by darsain** [comment]
If I understand correctly, instead of having a clearly visible seeking UI to click (which shows only when needed), you want an invisible area you have to guess if you are inside of when clicking?

> This function will be convenient for quick positioning but will not occupy a large screen area

Seekable timeline shows up only when you want to use it, i.e. when you move your mouse towards it, or toggle it with a key. If you don't need it, it doesn't occupy any space whatsoever, and since it's proximity based, it'll never show up on random mouse movements, so I can't accept this complaint.

If the UI shows up too soon for you, you can always tweak `proximity_min` and `proximity_max` values.

Really sorry, but I don't see any value in this, nor do I wish to maintain code that would support that. Having invisible magic control areas is bad design, and the whole point of uosc is to design a better UI that doesn't need that kind of stuff.

It seems to me that you are just used to this kind of behavior and want to mold a new tool to how the old one used to work, and since re-implementing torque/mpv-progressbar is not the goal of this project, I just can't oblige.
