### ISSUE TITLE
Extremely sluggish when using fullscreen, 3840x2160, 23.976 Hz

### ISSUE THREAD

**Issue by FCrane** [darsain/uosc#52]
Strange but very annoying issue:

When playing a UHD video on a monitor with 3840x2160 resolution and low refresh rate (e.g.23.976 Hz or 24 Hz), the UOSC interface becomes extremely sluggish and even faulty, when the player is in full screen mode! When I move the mouse near an element, it sometimes takes several seconds until it appears! If I keep moving the mouse, the element won't appear at all! Also, fading out stutters extremely (meaning it fades a bit, stops fading for a second or two, fades some more, stops again, etc.) and sometimes object don't even fade out completely but stay visible forever.

When exiting full screen and running the video in a window that covers the whole screen, it works perfectly fine! So it can't be a performance issue (CPU is at 1%, GPU at 30% during playback).

Also, when I set the monitor to 60 Hz and play the same video, the interface runs perfectly smooth! This seems so strange because at 60 Hz, the system load should be even higher.

So why does UOSC not work correctly in low screen refresh rates? When both the video and the screen run at 24 Hz, it should even work smoother than if the rates mismatch...

Thanks!

**Comment by FCrane** [comment]
Hi again!

I think I figured out, what the problem is: if 
hwdec = yes
then the problem occurs. If I set
hwdec = dxva2
everything is smooth in full screen as well as windowed mode!

Maybe this finding can help others too.

Thanks!

**Comment by darsain** [comment]
Yeah this is unrelated to uosc. Meaning, it has to be mpv, mpv configuration, or maybe drivers issue.
Performance is really important to me so uosc is made to be as efficient as possible, and should definitely not be causing any sluggishness.

It may feel sluggish sometimes when low fps video is playing, because mpv then syncs UI rendering frequency with video, but there is nothing I can do about that. It's an mpv limitation.

Thx for sharing the solution to your problem though!
