### ISSUE TITLE
Title bar appears when opening a file and doesn't go away until I move the mouse

### ISSUE THREAD

**Issue by zloom31** [darsain/uosc#65]
The title bar of uosc appears when I open a file in any file browser/from terminal and doesn't go away until I move my mouse. It doesn't matter where my mouse is when I start video playback, it still appears until I move my mouse. Is there anyway to make it so that it doesn't appear when I load a file and only triggers on mouse over?

I'm on linux.

Below is everything from my uosc.conf relating to the top bar. I have border=no in my mpv.conf.
```
top_bar=no-border
top_bar_size=60
top_bar_size_fullscreen=66
top_bar_persistency=
top_bar_controls=no
top_bar_title=yes
```

**Comment by tomasklaen** [comment]
Yeah on linux, mpv is reporting initial cursor position incorrectly as x,y = 0,0, so uosc thinks the cursor is in the top left corner until you move the mouse and it gets a correct position.

Fixed in 11a231c618d72fce234efe7f1b6d06df25a6c594 by treating 0,0 as infinity,infinity.

Should probably be also reported to mpv.
