### ISSUE TITLE
Lua error

### ISSUE THREAD

**Issue by sbstratos79** [darsain/uosc#73]
I get this error on Fedora 35. 
```
Lua error: [string "/home/sbstratos79/.config/mpv/scripts/uosc.lua"]:1958: '=' expected near 'continue'
```
uosc works completely fine on flatpak version of mpv.
This only happens on the version provided by Fedora 35.

I am using the latest version of uosc.
mpv 0.34.1

**Comment by tomasklaen** [comment]
Maybe that version of mpv is compiled with an older or different version of lua that doesn't support goto? Just a guess though. The code is otherwise fine, as as you've said, it works fine everywhere else.

The only fix from my side would be to refactor the code to not use `goto continue` hack to add `continue` clause to loops, which would be annoying :(

**Comment by sbstratos79** [comment]
You are right. A version mismatch seems to be the case. Is there a way for me to fix this besides just hoping that the next release of mpv on Fedora is compiled with newer Lua version?

**Comment by tomasklaen** [comment]
I imagine only compiling your own? Or just use the flatpak version.

But I'm not that experienced with linux, and even less with fedora, so can't be of more assistance.

**Comment by sbstratos79** [comment]
Thanks. I will close this issue.
