### ISSUE TITLE
Pause indicator

### ISSUE THREAD

**Issue by po5** [darsain/uosc#8]
Display something when pausing/unpausing.

It's something I want but can see it being distracting for some, there should be a toggle.

**Comment by darsain** [comment]
I cannot express how much I hate when I pause a video to look at, or screenshot, part of the video, and there is a pause indicator in the way. I've never understood why silence and frozen picture is not enough, and designers still feel the need to cover the picture with some icons. It also serves no purpose since it doesn't convey any additional information that silence+freeze isn't already.

But maybe it's just me and more people actually enjoy this, so since it's very simple to implement with hopefully 0 maintenance tax, I'll add it, but it's going to be off by default :)
