### ISSUE TITLE
UI elements are too small on high resolution displays

### ISSUE THREAD

**Issue by accelyte** [darsain/uosc#81]
I am currently on a 14" 2880x1800 laptop display with 200% scaling enabled in Windows settings.

Without using uosc:
![image](https://user-images.githubusercontent.com/95587932/175807498-19a4cdfd-6118-4059-8430-3ae52533170f.png)

Using uosc (empty `uosc.conf`):
![image](https://user-images.githubusercontent.com/95587932/175807563-d5b9089e-ae5d-46b4-93eb-9a21a65302cb.png)
![mpv-220626-1715-2hNyajMDsT](https://user-images.githubusercontent.com/95587932/175807573-178be8be-73c0-45c8-9b2b-7d399bbc2fe1.png)

The default mpv OSD seems to respect the Windows scale factor, but uosc does not. I'm aware that there are granular size configurations, but it would be a lot of work just to get each UI element working properly.
Is it possible to configure uosc to follow the Windows UI scale factor? If not, is it possible to configure the scale factor of all UI elements at once (maybe `scale=1`)?

**Comment by tomasklaen** [comment]
Damn, I thought this was handled automatically by drawing APIs. I guess not.

I did some digging and mpv documentation mentions nothing about how to handle window scaling, or at least I couldn't find anything.

And the only thing I've noticed in the mpv's built in `osc.lua` is that they use `mp.get_osd_size()` instead of `mp.get_property_native('osd-dimensions')` which is what I've been using. Maybe the `mp.*` thingy returns scaling aware values.

I've switched it and you can try it here: https://github.com/darsain/uosc/raw/scaling/uosc.lua

Please report if anything changed or still the same.

In case the scaling is now correct, expect cursor to not work properly because I haven't implemented scaling aware cursor position translation yet, this is just to test the rendering.

**Comment by accelyte** [comment]
I tried your new script on a clean install of mpv:
![image](https://user-images.githubusercontent.com/95587932/175887695-928b57eb-dc63-44e2-93c7-cab3bfb37d4a.png)
The issue persists.

**Comment by tomasklaen** [comment]
Then I actually don't know what mpv's osc is doing to scale properly. I'll have to dig in deeper, or maybe ask on their irc when I have some time.
